server:
  port: 8080

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: buscador-service
          uri: lb://buscador-service
          predicates:
            - Path=/products/**
        - id: operador-service
          uri: lb://operador-service
          predicates:
            - Path=/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
